### 예외와 예외 클래스

- 일반 예외
  - 컴파일러가 예외 처리 코드 여부를 검사하는 예외
- 실행 예외(Runtime exception)
  - 컴파일러가 예외 처리 코드 여부를 검사하지 않는 예외
  - 해당 예외에 대한 처리 코드가 없어도 된다
  - 단, 처리 코드가 없다면 프로그램은 즉시 종료된다.
- 모든 에러와 예외 클래스는 Throwable을 상속받아 만들어짐
- 예외 클래스는 java.lang.Exception 클래스를 상속받음

### 예외 처리 코드

- try-catch-finally
- finally는 예외 발생 여부와 상관 없이 항상 실행된다.
- 예외 정보를 얻는 세 가지 방법은 다음과 같다.

```java
System.out.println(e.getMessage()); // 1
System.out.println(e.toString()); // 2
e.printStackTrace(); // 3
```

- 1은 예외가 발생한 이유만 리턴한다.
- 2는 예외의 종류도 리턴한다.
- 3은 예외가 어디서 발생했는지 추적한 내용까지 출력한다.

### 예외 종류에 따른 처리

- try문 안에 다양한 예외가 발생할 수 있다.
- catch 블록을 여러 개 작성하여 특정 예외만을 핸들링할 수 있다.
- 처리해야 할 예외 클래스들이 상속 관계인 경우, 하위 클래스의 catch를 먼저 작성해야 한다.
  - 예외가 발생하면 catch문이 작성된 순서대로 핸들링하는데, 상위 클래스가 상단에 있을 경우, 상위 클래스가 하위 클래스를 포함하기 때문이다.
  - ```java
        catch (Exception E) {
            ~~
        } catch (ArrayIndexOutOfBoundsException e) {
            // Exception 아래에 Array~ 예외를 포함하기 때문에 이렇게 작성하면 정상적인 핸들링이 불가능하다.
        }
    ```
- 두 개 이상의 예외를 하나의 catch에서 다루고 싶은 경우 `catch(Exception1 | Exception2 e)`와 같이 하면 된다.

### 리소스 자동 닫기

- 파일을 열고 닫을 때에는 FileInputStream("filename.txt"); 를 사용하자
- 파일을 열고 닫을 때 예외가 발생할 수 있으므로 try-catch 안에서 이를 수행해야 한다.
- 이를 쉽게 하려면 다음과 같이 하자.

```java
try(FileInputStream fis = new FileInputstream("file.txt")) {
    ~
} catch(IOException e) { ~ }
```

- 이를 try-with-resources 구문이라고 한다.
- 이 블록을 사용하기 위해서는 java.lang.AutoCloseable 인터페이스를 구현하여 close()메서드를 재정의해야 한다.

```java
public class FileInputStream implements AutoCloseable {
    @Override
    public void close() thorws Exception {}
}
```

- 최신 자바 버전은 try 괄호 밖에서 파일 변수를 선언해도 된다.

```java
FileInputStream fis1 = new FileInputStream("file1.txt");
FileInputStream fis2 = new FileInputStream("file2.txt");
try(fis1; fis2) {
    ~
} catch (IOExcetion E) {}
```

### 예외 떠넘기기

- 메서드 내부에서 예외가 발생할 때 throws를 사용하여 예외를 밖으로 던질 수 있다.
- 밖으로 던진다는 의미는, 그 메서드를 실행한 곳에 가서 처리하라는 의미이다. 이 메서드가 아니라.
- 해당 메서드에서 예외를 처리하지 않을 때 사용한다.

```java
public class ThrowExample {
    public static void main(String[] args) {
        try {
            findClass();
        } catch (ClassNotFoundException e) { // 던져진 에러를 여서 받는다.
            System.out.println("처리");
        }
    }

    public static void findClass() throws ClassNotFoundException {
        Class.forName("java.lang.String2"); // 에러 발생 시 여기서 처리하지 않고 던진다.
    }
}
```

- 처리해야 할 예외 클래스가 많은 경우 throws Exaception | Throwable로 걍 싹 다 던지면 된다.

### 사용자 정의 예외

- 일반 예외는 Exception의 자식으로, 실행 예외는 RuntimeException의 자식 클래스로 선언한다.
- 사용자 정의 예외는 기본 생성자와 예외 메시지를 입력받는 생성자, 총 2개의 생성자를 작성한다.
- getMessage()메서드를 사용하기 위함이다.

```java
public class InsufficientException extends Exception {
    public InsufficientException() {} // 기본 생성자
    public InsufficientException(String message) {
        super(message); // 부모 생성자 호출. getMessage에 들어갈 message를 입력함.
    }
}
```

- 헷갈리지 말자.
- <mark>throw는 메서드 선언 시 사용. 이런 예외를 던질 수 있다. throws는 진짜 예외 객체를 생성해서 던지는 용도.</mark>
-
